drop table if exists bookmarks;

create table bookmarks (
    id INTEGER primary key generated by default as identity,
    title TEXT NOT NULL,
    url TEXT NOT NULL,
    rating INTEGER NOT NULL,
    description TEXT
);

-- insert into bookmarks (title, url, rating, description)
-- values
--     ('Netflix', 'netflix.com', 5, 'Best place to watch The Office'),
--     ('Facebook', 'facebook.com', 4, 'Social networking and distractions'),
--     ('Reddit', 'reddit.com', 4, 'News and distractions'),
--     ('LinkedIn', 'linkedin.com', 5, 'Hire me pls'),
--     ('Amazon', 'amazon.com', 5, 'Online shop for all your office supply needs'),
--     ('Thinkful', 'thinkful.com', 4, 'Learn to code!'),
--     ('Dunderpedia', 'theoffice.fandom.com/wiki/The_Office', 5, 'Everything you need to know about The Office, and more!'),
--     ('Office Depot', 'officedepot.com', 1, 'Main competitor to Dunder Mifflin, overall awful place to shop'),
--     ('Official website of Scranton, PA', 'scrantonpa.gov', 3, 'Learn the facts and figures of Scranton, PA'),
--     ('Youtube', 'youtube.com', 4, 'Spend hours watching clips and blooper reels of The Office here');

